# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 07:20
from __future__ import unicode_literals

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_entry_top_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200, verbose_name='主题')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.TextField(verbose_name='相关描述')),
            ],
            options={
                'verbose_name': '试题分类',
                'verbose_name_plural': '试题分类',
            },
        ),
        migrations.CreateModel(
            name='Single_Q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend', models.BooleanField(default=False, verbose_name='重点题目')),
                ('title', models.CharField(max_length=200, verbose_name='题目简化版')),
                ('caption', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='题目')),
                ('answer', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='答案解析')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='标签')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam_Topic', verbose_name='归属主题')),
            ],
            options={
                'verbose_name': '单选题',
                'verbose_name_plural': '单选题',
            },
        ),
    ]
