# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20170829_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='single_q',
            old_name='answer',
            new_name='answer_detail',
        ),
    ]
