# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 10:43
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20170829_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_correct', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='选项1')),
                ('select2', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='选项2')),
                ('select3', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='选项3')),
                ('select4', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='选项4')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Single_Q', verbose_name='归属题目')),
            ],
        ),
    ]
