# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20170830_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill_answer',
            name='answer',
            field=models.CharField(default='', max_length=200, verbose_name='正确答案'),
        ),
        migrations.AlterField(
            model_name='single_q',
            name='answer',
            field=models.CharField(default='', max_length=200, verbose_name='正确选项'),
        ),
        migrations.AlterField(
            model_name='single_q',
            name='select_2',
            field=models.CharField(default='', max_length=200, verbose_name='选项2'),
        ),
        migrations.AlterField(
            model_name='single_q',
            name='select_3',
            field=models.CharField(default='', max_length=200, verbose_name='选项3'),
        ),
        migrations.AlterField(
            model_name='single_q',
            name='select_4',
            field=models.CharField(default='', max_length=200, verbose_name='选项4'),
        ),
    ]
