# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_wronganswerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='wronganswerinfo',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
