# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20170913_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlewronganswer',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
