# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_singlewronganswer_date_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlewronganswer',
            name='correct_times',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singlewronganswer',
            name='wrong_times',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
