# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20170913_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlewronganswer',
            name='first_is_right',
            field=models.BooleanField(default=False, verbose_name='首答正确'),
        ),
    ]
