# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_singlewronganswer_first_is_right'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlewronganswer',
            name='first_is_right',
        ),
        migrations.AddField(
            model_name='singlewronganswer',
            name='first_right_times',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
