# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_auto_20170913_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Topic_Second',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200, verbose_name='二级主题')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.TextField(verbose_name='相关描述')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam_Topic', verbose_name='归属主题')),
            ],
            options={
                'verbose_name': '试题分类',
                'verbose_name_plural': '试题分类',
            },
        ),
        migrations.AddField(
            model_name='fill_q',
            name='topic_second',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.Exam_Topic_Second', verbose_name='归属二级主题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='single_q',
            name='topic_second',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='exam.Exam_Topic_Second', verbose_name='归属二级主题'),
            preserve_default=False,
        ),
    ]
