# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_auto_20170915_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam_topic_second',
            options={'verbose_name': '试题二级分类', 'verbose_name_plural': '试题二级分类'},
        ),
        migrations.RemoveField(
            model_name='single_q',
            name='topic_second',
        ),
        migrations.AddField(
            model_name='single_q',
            name='topic_second',
            field=models.ManyToManyField(blank=True, to='exam.Exam_Topic_Second', verbose_name='归属二级主题'),
        ),
    ]
