# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_auto_20170915_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill_q',
            name='topic_second',
        ),
        migrations.AddField(
            model_name='fill_q',
            name='topic_second',
            field=models.ManyToManyField(blank=True, to='exam.Exam_Topic_Second', verbose_name='归属二级主题'),
        ),
    ]
