# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_auto_20170915_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_topic_second',
            name='recommend',
            field=models.BooleanField(default=False, verbose_name='推荐'),
        ),
    ]
