# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_exam_topic_second_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_topic_second',
            name='recommend',
            field=models.BooleanField(default=False, verbose_name='重要主题'),
        ),
    ]
