# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0023_auto_20170915_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill_answer',
            name='answer4',
            field=models.CharField(default='', max_length=200, verbose_name='正确答案4'),
        ),
    ]
