# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0024_auto_20170915_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill_answer',
            name='answer',
        ),
        migrations.AddField(
            model_name='fill_answer',
            name='answer1',
            field=models.CharField(default='', max_length=200, verbose_name='正确答案1'),
        ),
    ]
