# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0026_remove_fill_q_blank_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillWrongAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_fill_n', models.PositiveIntegerField(default=0)),
                ('wrong_answer', models.CharField(default='', max_length=200, verbose_name='用户答案')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('correct_times', models.PositiveIntegerField(default=0)),
                ('wrong_times', models.PositiveIntegerField(default=0)),
                ('first_right_times', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Fill_Q', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='归属用户')),
            ],
            options={
                'verbose_name': '错题本_填空题',
                'verbose_name_plural': '错题本_填空题',
            },
        ),
    ]
