# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0027_fillwronganswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fillwronganswer',
            old_name='wrong_answer',
            new_name='wrong_answer_n',
        ),
        migrations.RemoveField(
            model_name='fillwronganswer',
            name='wrong_fill_n',
        ),
    ]
