# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0028_auto_20170926_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fillwronganswer',
            old_name='wrong_answer_n',
            new_name='wrong_answer',
        ),
        migrations.AddField(
            model_name='fillwronganswer',
            name='wrong_fill_n',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
