# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 06:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0030_auto_20170926_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('img', models.FileField(upload_to='exam')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='ExaminationPaperChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('examination_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.ExaminationPaper')),
            ],
            options={
                'verbose_name': '专题章节',
                'verbose_name_plural': '专题章节',
            },
        ),
        migrations.CreateModel(
            name='ExaminationPaperItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.ExaminationPaperChapter')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '试卷具体试题',
                'verbose_name_plural': '试卷具体试题',
            },
        ),
        migrations.CreateModel(
            name='ExaminationPaperType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '试卷类型',
                'verbose_name_plural': '试卷类型',
            },
        ),
        migrations.AddField(
            model_name='examinationpaper',
            name='ExaminationPaper_Type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.ExaminationPaperType'),
        ),
        migrations.AddField(
            model_name='examinationpaper',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
