# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0031_auto_20170928_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinationpaper',
            name='img',
        ),
    ]
