# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0032_remove_examinationpaper_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examinationpaperchapter',
            options={'verbose_name': '试卷模块', 'verbose_name_plural': '试卷模块'},
        ),
        migrations.RenameField(
            model_name='examinationpaper',
            old_name='ExaminationPaper_Type',
            new_name='exam_paper_type',
        ),
    ]
