# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0033_auto_20171002_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillwronganswer',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='显示'),
        ),
        migrations.AlterField(
            model_name='fillwronganswer',
            name='correct_times',
            field=models.PositiveIntegerField(default=0, verbose_name='答对次数'),
        ),
        migrations.AlterField(
            model_name='fillwronganswer',
            name='first_right_times',
            field=models.PositiveIntegerField(default=0, verbose_name='第一次做对'),
        ),
        migrations.AlterField(
            model_name='singlewronganswer',
            name='correct_times',
            field=models.PositiveIntegerField(default=0, verbose_name='答对次数'),
        ),
        migrations.AlterField(
            model_name='singlewronganswer',
            name='first_right_times',
            field=models.PositiveIntegerField(default=0, verbose_name='第一次做对'),
        ),
    ]
