# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0035_singlewronganswer_is_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlewronganswer',
            name='is_show',
            field=models.PositiveIntegerField(default=1, verbose_name='显示'),
        ),
    ]
