# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0037_auto_20171012_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='single_q',
            name='status',
            field=models.CharField(choices=[('A', 'B'), ('C', 'D')], default='draft', max_length=10),
        ),
    ]
