# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0038_single_q_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='single_q',
            name='status',
        ),
        migrations.AlterField(
            model_name='single_q',
            name='answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=10, verbose_name='正确选项'),
        ),
    ]
