# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0039_auto_20180105_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_q',
            name='answer',
            field=models.CharField(default='', max_length=200, verbose_name='正确选项'),
        ),
    ]
