# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0040_auto_20180105_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_q',
            name='answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=10, verbose_name='正确选项'),
        ),
    ]
