# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0041_auto_20180105_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='single_q',
            name='select_2',
        ),
        migrations.RemoveField(
            model_name='single_q',
            name='select_3',
        ),
        migrations.RemoveField(
            model_name='single_q',
            name='select_4',
        ),
    ]
