# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0045_auto_20180110_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill_answer',
            name='is_only',
            field=models.BooleanField(default=True, verbose_name='答案形式确定'),
        ),
    ]
