# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0046_auto_20180114_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillwronganswer',
            name='killed_times',
            field=models.PositiveIntegerField(default=1, verbose_name='斩掉次数'),
        ),
        migrations.AddField(
            model_name='singlewronganswer',
            name='killed_times',
            field=models.PositiveIntegerField(default=1, verbose_name='斩掉次数'),
        ),
    ]
