# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0047_auto_20180208_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationpaperchapter',
            name='description',
            field=models.TextField(default='', max_length=200, verbose_name='模块描述'),
        ),
    ]
