# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0048_examinationpaperchapter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationpaperitem',
            name='question_value',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='', max_length=5, verbose_name='本题分值'),
        ),
        migrations.AlterField(
            model_name='examinationpaperchapter',
            name='title',
            field=models.CharField(max_length=250, verbose_name='标题'),
        ),
    ]
