# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-11 08:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0050_auto_20180209_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRecordRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateTimeField(auto_now_add=True, verbose_name='考试开始时间')),
                ('date_end', models.DateTimeField(verbose_name='考试结束时间')),
                ('time_limit', models.PositiveIntegerField(default=60, verbose_name='考试限制时间（分钟）')),
                ('description', models.TextField(default='', max_length=200, verbose_name='考试描述')),
                ('examination_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.ExaminationPaper', verbose_name='所属试卷')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSingleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='', max_length=200, verbose_name='用户答案')),
                ('question_value', models.PositiveIntegerField(default=2, verbose_name='本题分值')),
                ('score', models.PositiveIntegerField(default=2, verbose_name='本题得分')),
                ('is_right', models.BooleanField(default=True, verbose_name='正误')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='试卷提交时间')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('exam_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.ExamRecordRound', verbose_name='考试时间')),
                ('examination_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.ExaminationPaper', verbose_name='所属试卷')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Single_Q', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.AlterField(
            model_name='examinationpaperitem',
            name='question_value',
            field=models.PositiveIntegerField(default=2, verbose_name='本题分值'),
        ),
    ]
