# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-11 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0051_auto_20180211_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examrecordround',
            name='description',
        ),
        migrations.AddField(
            model_name='examrecordround',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='考试场次'),
        ),
        migrations.AlterField(
            model_name='examsinglerecord',
            name='exam_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.ExamRecordRound', verbose_name='考试场次'),
        ),
    ]
