# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-11 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0052_auto_20180211_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamSingleRecord',
            new_name='ExamRecordSingleDetail',
        ),
        migrations.AlterModelOptions(
            name='examrecordround',
            options={'verbose_name': '考试场次', 'verbose_name_plural': '考试场次'},
        ),
        migrations.AlterModelOptions(
            name='examrecordsingledetail',
            options={'verbose_name': '考试记录单选题', 'verbose_name_plural': '考试记录单选题'},
        ),
        migrations.AlterField(
            model_name='examrecordround',
            name='date_begin',
            field=models.DateTimeField(verbose_name='考试开始时间'),
        ),
    ]
