# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-11 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0053_auto_20180211_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='试卷提交时间')),
                ('exam_value', models.PositiveIntegerField(default=0, verbose_name='试卷总分值')),
                ('value_single', models.PositiveIntegerField(default=0, verbose_name='单选题分值')),
                ('value_fill', models.PositiveIntegerField(default=0, verbose_name='填空题分值')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='试卷得分')),
                ('score_single', models.PositiveIntegerField(default=0, verbose_name='单选题得分')),
                ('score_fill', models.PositiveIntegerField(default=0, verbose_name='填空题得分')),
                ('can_reexamine', models.BooleanField(default=False, verbose_name='重考')),
                ('reexamine_times', models.PositiveIntegerField(default=0, verbose_name='重考次数')),
                ('reexamine_remark', models.CharField(default='', max_length=200, verbose_name='重考备注')),
                ('exam_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.ExamRecordRound', verbose_name='考试场次')),
                ('examination_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.ExaminationPaper', verbose_name='所属试卷')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='考生')),
            ],
            options={
                'verbose_name': '考试记录',
                'verbose_name_plural': '考试记录',
            },
        ),
        migrations.AlterModelOptions(
            name='examrecordsingledetail',
            options={'verbose_name': '考试记录-单选题', 'verbose_name_plural': '考试记录-单选题'},
        ),
        migrations.RemoveField(
            model_name='examrecordsingledetail',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='examrecordsingledetail',
            name='date_update',
        ),
        migrations.AddField(
            model_name='examrecordsingledetail',
            name='exam_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.ExamRecord', verbose_name='所属考试'),
            preserve_default=False,
        ),
    ]
