# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-11 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0054_auto_20180211_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examrecord',
            old_name='score',
            new_name='exam_score',
        ),
    ]
