# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0055_auto_20180211_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examrecordsingledetail',
            name='exam_round',
        ),
        migrations.RemoveField(
            model_name='examrecordsingledetail',
            name='examination_paper',
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='reexamine_remark',
            field=models.CharField(default='无', max_length=200, verbose_name='重考备注'),
        ),
    ]
