# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 05:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0056_auto_20180212_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRecordFillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_value', models.PositiveIntegerField(default=2, verbose_name='本题分值')),
                ('answer', models.CharField(default='', max_length=200, verbose_name='用户答案')),
                ('fill_n', models.PositiveIntegerField(default=0, verbose_name='第N空')),
                ('score', models.PositiveIntegerField(default=2, verbose_name='本空得分')),
                ('is_right', models.BooleanField(default=False, verbose_name='正误')),
                ('exam_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.ExamRecord', verbose_name='所属考试')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Fill_Q', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '考试记录-填空题',
                'verbose_name_plural': '考试记录-填空题',
            },
        ),
        migrations.AlterField(
            model_name='examrecordsingledetail',
            name='is_right',
            field=models.BooleanField(default=False, verbose_name='正误'),
        ),
    ]
