# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0057_auto_20180213_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examrecordfilldetail',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='本空得分'),
        ),
        migrations.AlterField(
            model_name='examrecordsingledetail',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='本题得分'),
        ),
    ]
