# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_avatar',
            name='avatar',
            field=models.ImageField(default='avatar/default.jpg', upload_to='avatar/'),
        ),
    ]
