# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170823_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_avatar',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_Avatar',
        ),
    ]
