# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0004_auto_20170818_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Uncheck this box to make the comment effectively disappear from the site.', verbose_name='is public'),
        ),
    ]
