# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0006_auto_20170819_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
