# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0007_comment_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_last_name',
        ),
    ]
