# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 08:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170813_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['text'], 'verbose_name': '栏目', 'verbose_name_plural': '主题'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='topic',
        ),
        migrations.AddField(
            model_name='entry',
            name='topic',
            field=models.ManyToManyField(to='blog.Topic', verbose_name='归属主题'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=200, verbose_name='主题'),
        ),
    ]
