# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170815_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='create_time',
            new_name='date_added',
        ),
        migrations.AlterField(
            model_name='entry',
            name='recommend',
            field=models.BooleanField(default=False, verbose_name='推荐'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(verbose_name='相关描述'),
        ),
    ]
