# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170818_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='top_in',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
    ]
