# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_entry_top_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='完全不可见'),
        ),
        migrations.AddField(
            model_name='entry',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='登录可见'),
        ),
    ]
