# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_entry_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='is_private',
        ),
    ]
