# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': '专题', 'verbose_name_plural': '专题'},
        ),
        migrations.AlterModelOptions(
            name='subjectchapter',
            options={'verbose_name': '专题章节', 'verbose_name_plural': '专题章节'},
        ),
        migrations.AlterModelOptions(
            name='subjectitem',
            options={'verbose_name': '专题文章', 'verbose_name_plural': '专题文章'},
        ),
        migrations.AlterModelOptions(
            name='subjectstatictype',
            options={'verbose_name': '专题类别状态', 'verbose_name_plural': '专题类别状态'},
        ),
        migrations.AlterModelOptions(
            name='subjecttype',
            options={'verbose_name': '专题类别', 'verbose_name_plural': '专题类别'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='img',
            field=models.FileField(upload_to='subject'),
        ),
    ]
