# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_auto_20170823_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='read_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
